### ISSUE TITLE
Describe error handling in RPC responses

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#150]
Error message transfer and handling is an important part of distributed decentralized information system. Transport protocol implementations provide error handling mechanisms, however they differ from each other:
- [gRPC](https://grpc.io/docs/guides/error/) inherits [google API error model](https://cloud.google.com/apis/design/errors#error_model) that returns error code, string message and optional details (supported in limited gRPC implementations),
- [Twirp](https://github.com/twitchtv/twirp/blob/master/docs/errors.md) provides error code, string message and string key-value map for meta data.

NeoFS API does not define transport layer. Therefore it is required to describe error handling on top of all transport implementations. To do that we should:
- [ ] define enum of error types (or take it from gRPC or twrip implementation),
- [ ] define error structure with error type and string details,
- [ ] use error structure in `ResponseMetaHeader`.

**Comment by roman-khimov** [comment]
I think any solution that would allow me to do `errors.Is(err, apierrorslist.Something)` is fine.
