### ISSUE TITLE
Define container context in session token

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#156]
Container operations are similar to object operations in terms of permission delegation. Protocol gate implementations require permission delegation to operate with data on behalf of user. 

Permission delegation is done by session token. We should expand session token body with container context. Container context includes:
- verb (Put, Delete, SetEACL),
- container ID.

We ignore all reading verbs because data publicly available on side chain, therefore it is useless to grant access for such operations. 

There is a special container ID `JEKNVnkbo3jma5nREBBJCDoXFVeKkD56V3xKrvRmWxFG` (32 bytes of 0xFF) that should be interpreted as a wild card for the node. Node with delegated permissions can do specified operation with any user's container.

**Comment by cthulhu-rider** [comment]
Alternative options for generalizing containers:

1. explicit boolean field in context, if `true` -> all containers;
2. container ID is unset -> all containers.

**Comment by alexvanin** [comment]
>     1. explicit boolean field in context, if `true` -> all containers;
> 
>     2. container ID is unset -> all containers.

Agree with (1). As for (2), it may be quite hard to detect it in code (ContainerID can be a `nil`, it can be empty structure with `nil` fields, both are valid somehow).
