### ISSUE TITLE
Support multiple addresses in node info

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#160]
Storage node should be able to announce multiple addresses because it can service multiple networks. We have to make sure that `repeated string address = 2 [json_name = "address"];` in `netmap.NodeInfo` structure does not break compatibility.

**Comment by alexvanin** [comment]
As @cthulhu-rider mentioned, we need to check JSON compatibility as well.

**Comment by cthulhu-rider** [comment]
As expected, the proposed change will break JSON compatibility (not binary). 

Similar alternatives:

1. dedicated field `repeated string extra_addresses`;
2. well-known attribute.

Alternative format: csv in `address` field.

**Comment by alexvanin** [comment]
As soon as we
1) do not support any native JSON transport implementation yet,
2) do not sign or work with `NodeInfo` JSON structure in NeoFS ACL (unlike session tokens, for example),
3) keep binary compatibility,

I am ok with this JSON compatibility break.

**Comment by cthulhu-rider** [comment]
@alexvanin, I cannot agree that we can afford to break JSON compatibility even with missing applications. Apps that will use versions `>2.7` should be able to work with `2.7` nodes.
