### ISSUE TITLE
Common prefix match type in object search

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#164]
Different protocol gateways use attributes with directory path values to emulate file system directory structure. To simplify gateways development and to have a common approach on this, we should consider a "COMMON_PREFIX" match type for object search queries.

**Comment by realloc** [comment]
Use cases:
- S3 gateway prefix filter for object listing
- File gateway prefix search for directory emulation
- HTTP gateway FilePath prefix serach for index generation

**Comment by alexvanin** [comment]
Consider objects with `Filename` attrubte.
```
object1    Filename: /photos/2021/march/crab.jpg
object2    Filename: /photos/2021/july/cat.jpg
object3    Filename: /photos/2021/july/dog.jpg
```

Search query with `Filename COMMON_PREFIX /photos/2021/july` will return object2 and object3 IDs. Is it correct?

**Comment by realloc** [comment]
> Search query with `FilePath COMMON_PREFIX /photos/2021/july` will return object2 and object3 IDs. Is it correct?

Yes, that's the expected result.
