### ISSUE TITLE
Expand NetworkInfo information with more data

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#172]
After https://github.com/nspcc-dev/neo-go/issues/2160 we can expand `NetworkInfo` message with details about side chain:
- Ms per block,
- ... ?

Also we can include NeoFS global configuration records as a list of key/value (both repeated bytes).
Keys are hex encoded strings and values ara raw data from netmap contract.

**Comment by cthulhu-rider** [comment]
I'd also add list of keys and format of corresponding values.

**Comment by cthulhu-rider** [comment]
@alexvanin are u sure that keys are hex-encoded strings? Seems like Netmap contract stores UTF-8 strings. Or we want to encode them during communication?

**Comment by alexvanin** [comment]
> @alexvanin are u sure that keys are hex-encoded strings? Seems like Netmap contract stores UTF-8 strings. Or we want to encode them during communication?

You are right, they are simple UTF-8 encoded strings and should stay this way.
