### ISSUE TITLE
Expand placement policy with subnetwork field

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#179]
The best way to filter storage nodes of subnetwork is to define subnetwork ID directly in placement policy. 

UPD 16.11 @cthulhu-rider

1. Define `refs.SubnetID` type with single numerical field and describe:
- string format;
- binary format.

Null value should refer to zero subnet.

2. Add `subnet` field to `PlacementPolicy` message. Write the docs how it affects placement building.

**Comment by cthulhu-rider** [comment]
I suggest to define subnet ID as a type similar to other identifiers.
