### ISSUE TITLE
Return detail with server's magic number when it is incorrect

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#187]
Related to https://github.com/nspcc-dev/neofs-api/issues/82

In this issue we return `WRONG_MAGIC_NUMBER` error if magic was not set correctly. This error should return new detail that includes server's magic number. With it, clients without knowledge of the magic number, will be able to fetch this number and use it for later requests.

**Comment by realloc** [comment]
This issue is also related to version auto-negotiation. If both version and magic are wrong, the version should be taken from the same error response to avoid additional messaging cycle.
