### ISSUE TITLE
Create status codes for session-related errors

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-api#191]
Currently there are 2 candidates https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/util/key.go#L13

**Comment by alexvanin** [comment]
Also `errSessionTokenExpired` may be redundant on API level. Storage node will never produce such error after https://github.com/nspcc-dev/neofs-node/issues/1133. If token is expired but still available on the storage node, it can return API error of token not found anyway.

**Comment by fyrchik** [comment]
I think there is still a race condition in case of token expiration, so it is possible to get expired token from storage.

**Comment by alexvanin** [comment]
> I think there is still a race condition in case of token expiration, so it is possible to get expired token from storage.

It is. My point was that those errors are pretty much the same? If it is expired and if it was not found, they both indicate that client has to renew session token. Maybe it can be encoded as a detail, not the separate error code. I am not completely sure about that, though.

**Comment by fyrchik** [comment]
I agree they are essentially the same, just that an error message in case of expired token can be confusing. Maybe user-facing software should just tell `token was not found  or has expired`, this way one status is enough. Anyway both errors should be processed in an equal fashion.
