### ISSUE TITLE
Clarify object address field in object context of session token

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#202]
It seems that we currently ignore value of object address in session token (related https://github.com/nspcc-dev/neofs-node/issues/1191).
https://github.com/nspcc-dev/neofs-api/blob/f6dad19bef26a049e05eaedfebf90852697c03a7/session/types.proto#L44

It is not quite clear what address it should contain in case of `DELETE` and `SEARCH` operations. Also is it possible to have wildcard for different addresses? We need more details about that.

**Comment by alexvanin** [comment]
Addition: this field in fact is used by node. By I am not sure it is correct. See [useObjectIDFromSession](https://github.com/nspcc-dev/neofs-node/blob/09db5e387d46c19996ff53fa4fa8ed0c0472103c/pkg/services/object/acl/acl.go#L510) invocation references.

**Comment by cthulhu-rider** [comment]
We've inspired within https://github.com/nspcc-dev/neofs-node/issues/1420 to make objects in session context `repeated`. This will allow:

- issue a single session for a group of objects
- gather split-chain within single session

We can either:

1. make existing field `repeated`: this will allow to issue session for objects from different containers (is this really needed?)
2. deprecate address field, and add `refs.ContainerID container_id` field and `repeated refs.ObjectID id_list`
