### ISSUE TITLE
Container ID of eACL table in BearerToken needs clarification

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#207]
In recent storage node implementations (latest: neofs-node v0.27.5) eACL processing ignores `container_id` filed of `eacl_table` in `BearerToken` message. It has benefits for S3 gateway, because `auth-mate` app can create single bearer token and gateway will use it for all user's buckets. 

We should make it a part of the specification. Props to @KirillovDenis

**Comment by fyrchik** [comment]
Is it possible to give a user access to a one specific container then?

**Comment by alexvanin** [comment]
> Is it possible to give a user access to a one specific container then?

I guess it should be possible if bearer token specifies exact container ID value.
