### ISSUE TITLE
Require at least one field of `object.SplitInfo` to be set

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api#219]
In current implementation protocol doesn't impose restrictions on the presence of fields in `object.SplitInfo` message in `ObjectService` service. However, the absence of all fields is an incorrect response: it is not enough just to beacon about a fragmented object, you need to give a hook to the assembly.

## Proposal
Require at least one field to be set.

P.S. proposal breaks backward compatibility of the protocol, however, this requirement was always implied and was simply not explicitly stated.

**Comment by roman-khimov** [comment]
v2 split is validated all around, so nothing to do here.
