### ISSUE TITLE
Extend object notification message

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-api#226]
Sometimes the additional user-defined info is required in notification message. For example https://github.com/nspcc-dev/neofs-s3-gw requires additional object address and object filename in notification message.

It would be nice to have another attribute (e.g. `__NEOFS__TICK_DATA`) that contains arbitrary utf-8 string (perhaps with max size) that is also included into message (e.g. separated by some special character) along with object address.

**Comment by cthulhu-rider** [comment]
declined by #282, should be implemented on application side
