### ISSUE TITLE
Add a well-known attribute that defines a list of the attributes that must be inherited

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-api#236]
Add a new well-known object attribute. It should store a list of the attributes that *should/must* be inherited by the child objects if the original object split has happened.

That attribute also *should/must* be inherited.

**Comment by cthulhu-rider** [comment]
any explanations why? Child objects are on system layer, users dont care about it, only about root objects. More data to transfer, more to store. I expect a description of all the problems that can be solved by this feature

could be even less relevant after #264

**Comment by cthulhu-rider** [comment]
> Because of https://github.com/nspcc-dev/neofs-node/issues/1676 and https://github.com/nspcc-dev/neofs-spec/issues/75?

i didnt see these refs in the issue until this comment. Would be nice to mention them when creating an issue. Now, finally, we have some context

**Comment by roman-khimov** [comment]
It seems that with the new slicing scheme we don't need to inherit anything, you can always get attributes from the `init` object.

**Comment by carpawell** [comment]
> we don't need to inherit anything

Sure, this issue is outdated.
