### ISSUE TITLE
Make it clear that `EXPIRATION_EPOCH` is the last "available" epoch for all entities

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-api#253]
Check all the descriptions/comments. Related to regular and irregular objects, tokens.

**Comment by cthulhu-rider** [comment]
I suggest to either
1. exlude session and bearer tokens since it's a nonsense to use well-known naming with a change of meaning
2. stop reflecting JWT notations in NeoFS tokens

**Comment by carpawell** [comment]
If i have to choose, i would do `2.`. But also, as @realloc says JWT is about seconds while epoch is about minutes and even hours. JWT allows inevitable time delta which means "somewhen near that second expiration should happen" so it is not that strict in the real world.

/cc @fyrchik.

**Comment by realloc** [comment]
As @carpawell has already mentioned, we live in another time model and technically do the same thing as JWT does with X seconds splay on token expiration checks.

**Comment by cthulhu-rider** [comment]
IMO in most cases user wants to set expiration epoch - the timestamp when its product becomes unavailable. If it actually wants to set _last available_ claim, he just sets next epoch as an _exp_ claim. I don't see any reason to go off specification (if you fix the desire to follow it).

**Comment by realloc** [comment]
Let's stick to how we treat expiration epoch for objects.
