### ISSUE TITLE
Payload checksum type is not fixed

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-api#304]
Object header has payload checksums (not a homomorphic one) and there is no restriction about hashing algorithm. However, in practice, it is fixed and there is no sense in using TZ hash in regular hashing.

## Current Behavior
Hash is not fixed and our nodes' behavior is undefined if we meet such objects. E.g., it is impossible to search by such hashes: https://github.com/nspcc-dev/neofs-sdk-go/blob/256513c1b29bbb59326eecdc0ae669cc67e33155/object/search.go#L336-L341.  

## Expected Behavior
Objects hashing with any algo that is not sha256 should be prohibited. 

## Possible Solution
Add comments to this field.

## Steps to Reproduce
Use your eyes, look at https://github.com/nspcc-dev/neofs-api/blob/01229b49e9165e693a48e2b96ccad528df34b55e/object/types.proto#L87-L88.

## Regression
No.

**Comment by roman-khimov** [comment]
Fixed in #316.
