### ISSUE TITLE
Limit max REP value and number of REPs

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-api#307]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when nothing limits values. Sometimes, I need to think about limitations in real cases (e.g., we have contracts, contracts have stack/memory/storage limits), and I do not know what to do and if it is possible to have 1024 replicas 1024 times or even more.

## Describe the solution you'd like
Check there are no unrealistic containers in our networks and add nice limits to API. 256 max REP value and 256 max numbers of REPs look good to me.

## Describe alternatives you've considered
1. Any other nice number: 128, 512, 1024. But 8 bits are traditionally a good pick.
2. Do not have limits at all. But it will be possible to fail in some unexpected things because of overflow. Also, I cannot imagine thousands of SNs in real networks and a person who needs this number of REPlicas.

## Additional context
https://github.com/nspcc-dev/neofs-contract/pull/438

**Comment by roman-khimov** [comment]
Refs. #171.

**Comment by roman-khimov** [comment]
Likely the REP value can be even lower, like 8. But the number of REPs is a bit different, imagine a good old CDN, we can have quite a number of `REP 1` for various regions. Like what we hear for Akamai is 

> network of over approximately 365,000 servers in more than 135 countries. These servers reside on roughly 1,350 of the world's networks

so 256 is the number for now.
