### ISSUE TITLE
Clean-up Accounting

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#33]
Most of Accounting functionality is now served by Smart Contract and there is no need to use NeoFS API for things other then requesting Balance.

**Comment by alexvanin** [comment]
There is no need in `MetaHeader` and `VerifyHeader` in  [balance request](https://github.com/nspcc-dev/neofs-api/blob/d03837ec37933c638613e37994fb3c5dd41d48c9/accounting/service.proto#L25). I would like to remove these fields as they removed in all container related requests.
