### ISSUE TITLE
Add key and signature types into Signature message

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#55]
NeoFS uses different key and signature types, but this knowledge is not reflected directly in protocol definitions, only in code.

`Signature` structure needs to have key type reference and signature algorithm reference.

**Comment by realloc** [comment]
As an alternative approach, we could consider using [multihash](https://github.com/multiformats/multihash) format for storing signature. However, if we add a `Signature` hash type field, functionally it would be almost the same thing. Need to discuss what's better in the long run.

**Comment by fyrchik** [comment]
I see 2 problems with multihash: 
1. The codec in header describes only the type of data, not the signature algorithm https://github.com/multiformats/multicodec/blob/master/table.csv. So `sha512` can mean both `ECDSA` and `EdDSA` and we still need another field).
2. It can be hard to add new algorithms there (for local regulations or custom requirements) without effectively forking the whole `multicodec` or `multihash` repo.

**Comment by cthulhu-rider** [comment]
Also we have some need to work with WalletConnect (c) @realloc
