### ISSUE TITLE
Node information request is missing in v2.0 API

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#59]
There is need to check if node is ready to serve requests and get basic information about it. Previously this functionality was in `Healthcheck` service.

We need to add some simple ping-pong functionality without implementation specifics. It could be `NodeInfo` structure request in `netmap` service.

**Comment by realloc** [comment]
I propose to add an rpc call to Netmap Service, that would provide only state of the node for ping-pong-like cases and full NodeInfo for updating nodes' local netmap view.

```protobuf
// Request to get NodeInfo from the particular node directly, not by just
// reading it from Netmap.
message LocalNodeInfoRequest {
  //Request body
  message Body {
    // Return only node State, not full NodeInfo message
    bool status_only = 1;
  }
  // Body of the balance request message.
  Body body = 1;

  // Carries request meta information. Header data is used only to regulate
  // message transport and does not affect request execution.
  neo.fs.v2.session.RequestMetaHeader meta_header = 2;

  // Carries request verification information. This header is used to
  // authenticate the nodes of the message route and check the correctness
  // of transmission.
  neo.fs.v2.session.RequestVerificationHeader verify_header = 3;
}
```

**Comment by alexvanin** [comment]
@realloc I don't mind to have this service in API, but node definitely should implement more specific health check services. How response will look like?
