### ISSUE TITLE
Put object version field in the begining of the object message

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#60]
Object version can be used in low-level processing when storage works with stream of raw bytes, e.g. object storage takes slice of bytes, cuts version field with some offset and then chooses appropriate unmarshaler function. To do so we should have object version field in the beginning of byte stream. 

Right now object version stored in the beginning of `Header` message. With incompatible protocol changes, header message may be moved inside `Object` message, so version offset may change between different protocol implementation. 

To avoid this, `Object` message can store version as a first field. But we should store version in `Header` message anyway, so it may be confusing.

Other solution -- to have an agreement to never change fields before `Header` in `Object` message.

**Comment by realloc** [comment]
We already had in mind that `Object` structure will be extended by adding more headers and should not have incompatible changes. It's not likely for `Object` to get incompatible changes breaking `Header.Version` field extraction.

Let's agree to never change fields before `Header` in `Object` message and keep `Version` field first in the `Header`.
