### ISSUE TITLE
Sidechain Magic number should be used in NeoFS requests

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-api#82]
To prevent theoretical replay attack, we need to have Sidechain Magic in NeoFS requests.

**Comment by alexvanin** [comment]
Would be nice to think about it after https://github.com/nspcc-dev/neofs-api/issues/127 and https://github.com/nspcc-dev/neofs-dev-env/issues/6

**Comment by alexvanin** [comment]
This issue was rollbacked because it would break backward compatibility without status codes. Now it should work fine. 

**Besides that** implement, status code for invalid message so the client can process that and downgrade request version number.
