### ISSUE TITLE
Validity of empty attribute values

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-api#86]
Objects and containers have attributes, a pair of key-value strings. Key should be always set but what about value? It seems like it is possible to set attribute with empty value: some sort of a tag for object or container. However this small detail requires extra changes in implementations. For example some key-value storages that can be used as a back-end storage, can't set empty values. Therefore you'll have some issues in implementing fast secondary index for attributes. 

We should either explicitly declare in neofs-api, that empty attribute values are valid or restrict them.

/cc @realloc

**Comment by realloc** [comment]
Metadata secondary index for keys with empty  values could be automatically considered 'true'.
