### ISSUE TITLE
Rename Operation to Operator

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api#88]
[netmap.Operation](https://github.com/nspcc-dev/neofs-api/blob/35baf1ebfb4d804256e2833cb292131fabf14040/netmap/types.proto#L9) enumerates operators between filters (`OR`, `EQ`, etc.). I think `Operation` term is more suitable for expressions like `f1 AND f2` , so I suggest renaming to `Operator`.

Note: renaming of the message won't break version compatibility.

**Comment by realloc** [comment]
This fields specifies what filtering operation should be applied to the key value during filter execution. I understand that operation is express by operator, however this Protobuf format can be translated to/from other presentations (JSON, SQL-like, Blockly etc) where it can be expressed in a different way. I suggest to leave this naming as it to avoid confusion.
